import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0b0d10',
  },
  phoneFrame: {
    flex: 1,
    maxWidth: 460,
    alignSelf: 'center',
    width: '100%',
    backgroundColor: '#101216',
    borderRadius: 34,
    overflow: 'hidden',
    borderColor: '#23262e',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.35,
    shadowRadius: 30,
    elevation: 8,
  },
  statusBar: {
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
  },
  statusTime: { color: '#eef0f3', fontSize: 14, fontWeight: '600' },
  statusPill: { width: 104, height: 26, backgroundColor: '#05060a', borderRadius: 16, position: 'absolute', left: '50%', top: 9, marginLeft: -52 },
  statusLabel: { color: '#eef0f3', letterSpacing: 1.2, fontWeight: '600' },
  appBar: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingBottom: 12 },
  backButton: { width: 34, height: 34, borderRadius: 10, backgroundColor: 'rgba(255,255,255,0.06)', alignItems: 'center', justifyContent: 'center' },
  backButtonSpacing: { marginBottom: 12 },
  backPlaceholder: { width: 34, height: 34 },
  backButtonText: { color: '#fff', fontSize: 20 },
  appBarTextWrap: { flex: 1, marginHorizontal: 12 },
  appBarEyebrow: { color: '#7f8792', fontSize: 11, fontWeight: '700', letterSpacing: 1.8, textTransform: 'uppercase' },
  appBarTitle: { color: '#f2f3f5', fontSize: 24, fontWeight: '800', letterSpacing: -0.4 },
  exposureBox: { alignItems: 'flex-end' },
  exposureLabel: { color: '#7f8792', fontSize: 9, fontWeight: '700', letterSpacing: 1.6 },
  exposureValue: { color: '#e8a33c', fontSize: 22, fontWeight: '900' },
  screenContent: { flex: 1, paddingHorizontal: 18, paddingTop: 14, paddingBottom: 18 },
  aboutButtonWrap: { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 4 },
  aboutButton: { backgroundColor: '#2f80ff', borderRadius: 999, paddingVertical: 10, paddingHorizontal: 14, alignSelf: 'flex-start', shadowColor: '#2f80ff', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.24, shadowRadius: 6, elevation: 2 },
  aboutButtonText: { color: '#fff', fontSize: 13, fontWeight: '800', letterSpacing: 0.2 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(4, 6, 10, 0.82)', justifyContent: 'center', paddingHorizontal: 14, paddingVertical: 20 },
  modalCard: { backgroundColor: '#181b21', borderRadius: 18, borderWidth: 1, borderColor: '#2a3040', padding: 16 },
  modalTitle: { color: '#f2f3f5', fontSize: 20, fontWeight: '800', marginBottom: 10 },
  modalText: { color: '#c7ccd4', fontSize: 13.5, lineHeight: 20, marginBottom: 8 },
  modalCloseButton: { marginTop: 8, backgroundColor: '#2f80ff', borderRadius: 12, paddingVertical: 11, alignItems: 'center' },
  modalCloseButtonText: { color: '#fff', fontSize: 14, fontWeight: '800' },
  scrollContent: { paddingBottom: 24 },
  heroCard: { backgroundColor: '#181b21', borderRadius: 18, borderWidth: 1, borderColor: '#262a33', padding: 18, marginBottom: 14 },
  eyebrow: { color: '#3a86ff', fontSize: 12, fontWeight: '700', letterSpacing: 1.8, marginBottom: 6 },
  title: { color: '#f2f3f5', fontSize: 24, fontWeight: '800', letterSpacing: -0.4, marginBottom: 6 },
  subtitle: { color: '#9aa0ab', fontSize: 14, lineHeight: 20 },
  schoolCard: { backgroundColor: '#181b21', borderRadius: 18, borderWidth: 1.5, borderColor: '#262a33', overflow: 'hidden', marginBottom: 12 },
  schoolColorBar: { height: 5 },
  schoolCardBody: { padding: 16 },
  schoolSwatchRow: { flexDirection: 'row', gap: 12 },
  swatchStack: { width: 52, alignItems: 'center' },
  swatchTop: { width: 52, height: 15, borderRadius: 5, borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)', marginBottom: 3 },
  swatchMiddle: { width: 52, height: 22, borderRadius: 2, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', marginBottom: 3 },
  swatchBottom: { width: 52, height: 11, borderRadius: 2, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  schoolMeta: { flex: 1 },
  schoolName: { color: '#eef0f3', fontSize: 19, fontWeight: '800', letterSpacing: -0.3 },
  schoolMascot: { color: '#3a86ff', fontSize: 12, fontWeight: '700', marginTop: 1 },
  schoolBlurb: { color: '#8890a0', fontSize: 12, lineHeight: 17, marginTop: 4 },
  schoolStars: { color: '#e8a33c', letterSpacing: 2, marginTop: 8 },
  schoolFooter: { marginTop: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  schoolHomeLabel: { color: '#7f8792', fontSize: 10, fontWeight: '700', letterSpacing: 1.5 },
  schoolHome: { color: '#c7ccd4', fontSize: 12.5, fontWeight: '600' },
  schoolWarning: { color: '#e0484d', fontSize: 12, marginTop: 10, lineHeight: 17 },
  schoolPb: { color: '#3a86ff', fontSize: 12.5, fontWeight: '600' },
  confirmCard: { backgroundColor: '#181b21', borderRadius: 20, borderWidth: 1, borderColor: '#262a33', overflow: 'hidden' },
  confirmHero: { height: 92, paddingHorizontal: 18, justifyContent: 'flex-end', paddingBottom: 12 },
  confirmTitle: { color: '#fff', fontSize: 24, fontWeight: '900', letterSpacing: -0.5 },
  confirmMascot: { color: '#fff', fontSize: 12, fontWeight: '700', letterSpacing: 1.2, marginTop: 3 },
  confirmBody: { padding: 16, paddingTop: 18 },
  statRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  statBox: { flex: 1, backgroundColor: '#20242c', borderRadius: 12, padding: 10, paddingHorizontal: 12 },
  statLabel: { color: '#6f7682', fontSize: 10, fontWeight: '700', letterSpacing: 1 },
  statValue: { color: '#eef0f3', fontSize: 15, fontWeight: '700', marginTop: 2 },
  blueText: { color: '#4d92ff' },
  sectionTitle: { color: '#7f8792', fontSize: 11, fontWeight: '700', letterSpacing: 1.5, marginBottom: 6 },
  sectionBody: { color: '#9aa0ab', fontSize: 13.5, lineHeight: 19, marginBottom: 16 },
  outlookRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 10, borderTopWidth: 1, borderTopColor: '#262a33' },
  outlookTextWrap: { flex: 1, marginRight: 10 },
  outlookLabel: { color: '#e5e8ed', fontSize: 13.5, fontWeight: '600' },
  outlookDesc: { color: '#7f8792', fontSize: 11.5, marginTop: 3 },
  outlookTag: { color: '#4d92ff', fontSize: 11, fontWeight: '700' },
  primaryButton: { marginTop: 16, backgroundColor: '#2f80ff', borderRadius: 15, paddingVertical: 16, alignItems: 'center', shadowColor: '#2f80ff', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 3 },
  primaryButtonDisabled: { backgroundColor: '#262b34', shadowOpacity: 0, elevation: 0 },
  primaryButtonText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  ghostButton: { marginTop: 16, borderWidth: 1, borderColor: '#3a3f49', borderRadius: 15, paddingVertical: 14, alignItems: 'center' },
  ghostButtonText: { color: '#dfe3e9', fontSize: 15, fontWeight: '700' },
  disabledText: { color: '#5f6672' },
  input: { marginTop: 12, backgroundColor: '#20242c', borderRadius: 14, borderWidth: 1, borderColor: '#2f3642', paddingHorizontal: 14, paddingVertical: 14, color: '#f2f3f5', fontSize: 16 },
  saveList: { marginTop: 16, gap: 10 },
  saveItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#181b21', borderRadius: 14, borderWidth: 1, borderColor: '#262a33', padding: 14 },
  progressRow: { flexDirection: 'row', gap: 6, marginBottom: 16 },
  progressBar: { flex: 1, height: 5, borderRadius: 4 },
  centerCard: { backgroundColor: '#181b21', borderRadius: 20, padding: 20, borderWidth: 1, borderColor: '#262a33' },
  challengeEyebrow: { color: '#7f8792', fontSize: 12, fontWeight: '700', letterSpacing: 2.5, textAlign: 'center' },
  challengeTitle: { color: '#fff', fontSize: 32, fontWeight: '900', letterSpacing: -0.6, textAlign: 'center', marginTop: 8 },
  challengeSub: { color: '#c7ccd4', fontSize: 14, textAlign: 'center', marginTop: 10, lineHeight: 20 },
  challengePanel: { backgroundColor: '#181b21', borderRadius: 18, borderWidth: 1, borderColor: '#262a33', padding: 18, marginTop: 18 },
  challengePanelLabel: { color: '#7f8792', fontSize: 11, fontWeight: '700', letterSpacing: 1.5, textAlign: 'center' },
  challengeTarget: { color: '#4d92ff', fontSize: 36, fontWeight: '900', textAlign: 'center', marginTop: 8 },
  challengeHint: { color: '#7f8792', fontSize: 13, textAlign: 'center', marginTop: 16, lineHeight: 19 },
  entryPanel: { backgroundColor: '#181b21', borderRadius: 18, borderWidth: 1, borderColor: '#262a33', padding: 22, marginTop: 18, alignItems: 'center' },
  entryLabel: { color: '#7f8792', fontSize: 12, fontWeight: '700', letterSpacing: 1.5, textTransform: 'uppercase', textAlign: 'center' },
  regionLabel: { marginTop: 18 },
  dropdownField: { marginTop: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#20242c', borderRadius: 14, borderWidth: 1, borderColor: '#2f3642', paddingHorizontal: 14, paddingVertical: 14 },
  dropdownValue: { color: '#f2f3f5', fontSize: 16 },
  dropdownPlaceholder: { color: '#6f7682', fontSize: 16 },
  dropdownChevron: { color: '#7f8792', fontSize: 12, marginLeft: 10 },
  dropdownBackdrop: { flex: 1, backgroundColor: 'rgba(4, 6, 10, 0.82)', justifyContent: 'center', paddingHorizontal: 22, paddingVertical: 40 },
  dropdownSheet: { width: '100%', maxWidth: 420, alignSelf: 'center', backgroundColor: '#181b21', borderRadius: 18, borderWidth: 1, borderColor: '#2a3040', paddingVertical: 8, maxHeight: '80%', overflow: 'hidden' },
  dropdownSheetTitle: { color: '#7f8792', fontSize: 12, fontWeight: '700', letterSpacing: 1.5, textTransform: 'uppercase', paddingHorizontal: 16, paddingTop: 8, paddingBottom: 10 },
  dropdownItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 14, borderTopWidth: 1, borderTopColor: '#23272f' },
  dropdownItemActive: { backgroundColor: '#1f2a3d' },
  dropdownItemText: { color: '#dfe3e9', fontSize: 16, fontWeight: '600' },
  dropdownItemTextActive: { color: '#4d92ff', fontWeight: '800' },
  devSliderWrap: { backgroundColor: '#241c14', borderRadius: 14, borderWidth: 1, borderColor: '#4a3a1f', padding: 14, marginBottom: 12 },
  devSliderLabelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  devSliderLabel: { color: '#e0a83c', fontSize: 11, fontWeight: '800', letterSpacing: 1.2 },
  devSliderValue: { color: '#f2f3f5', fontSize: 16, fontWeight: '800' },
  devSliderTrack: { marginTop: 12, height: 32, borderRadius: 16, backgroundColor: '#181b21', borderWidth: 1, borderColor: '#3a2f1a', justifyContent: 'center' },
  devSliderFill: { position: 'absolute', left: 0, top: 0, bottom: 0, borderRadius: 16, backgroundColor: 'rgba(224,168,60,.35)' },
  devSliderThumb: { position: 'absolute', width: 24, height: 24, borderRadius: 12, backgroundColor: '#e0a83c', marginLeft: -12, top: 4 },
  devSliderFootRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 10 },
  devSliderHint: { color: '#a8946a', fontSize: 11 },
  devSliderReset: { color: '#4d92ff', fontSize: 11, fontWeight: '700' },
  dropdownCheck: { color: '#4d92ff', fontSize: 16, fontWeight: '800' },
  stepperRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 14 },
  circleButton: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#262b34', alignItems: 'center', justifyContent: 'center' },
  circleButtonText: { color: '#fff', fontSize: 30, fontWeight: '300' },
  scoreValue: { minWidth: 96, color: '#fff', fontSize: 56, fontWeight: '900', textAlign: 'center', marginHorizontal: 20 },
  entryHint: { color: '#6f7682', fontSize: 12, marginTop: 12, textAlign: 'center' },
  toggleRow: { flexDirection: 'row', gap: 10, marginTop: 14 },
  toggleButton: { flex: 1, borderWidth: 1, borderColor: '#3a3f49', borderRadius: 13, paddingVertical: 9, paddingHorizontal: 20, alignItems: 'center' },
  toggleButtonActive: { backgroundColor: '#2f80ff', borderColor: '#2f80ff' },
  toggleButtonText: { color: '#dfe3e9', fontSize: 15, fontWeight: '700' },
  toggleButtonTextActive: { color: '#fff' },
  resultEmoji: { fontSize: 56, textAlign: 'center', marginBottom: 4 },
  resultHeadline: { fontSize: 28, fontWeight: '900', textAlign: 'center' },
  tabRow: { flexDirection: 'row', marginBottom: 10, paddingHorizontal: 8 },
  tabButton: { flex: 1, paddingVertical: 12, borderBottomWidth: 2.5, borderBottomColor: 'transparent', alignItems: 'center' },
  tabText: { fontSize: 15, fontWeight: '700', letterSpacing: 0.5 },
  scheduleRow: { flexDirection: 'row', alignItems: 'center', borderRadius: 15, borderWidth: 1.5, padding: 13, marginBottom: 10 },
  badge: { width: 38, height: 38, borderRadius: 11, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  badgeText: { fontSize: 15, fontWeight: '800' },
  rowTextWrap: { flex: 1 },
  rowTitle: { color: '#e8ebf0', fontSize: 15, fontWeight: '700' },
  rowSub: { color: '#828a96', fontSize: 12, marginTop: 1 },
  scheduleResult: { color: '#4d92ff', fontSize: 14, fontWeight: '800', textAlign: 'right' },
  depthList: { marginTop: 6 },
  depthItem: { flexDirection: 'row', alignItems: 'center', borderRadius: 13, borderWidth: 1.5, padding: 11, marginBottom: 8 },
  depthPos: { width: 30, fontSize: 19, fontWeight: '900', textAlign: 'center' },
  avatar: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', marginHorizontal: 10 },
  avatarText: { fontSize: 13, fontWeight: '800' },
  depthMove: { fontSize: 13, fontWeight: '700' },
  scoutPanel: { backgroundColor: '#181b21', borderRadius: 18, borderWidth: 1, borderColor: '#262a33', padding: 24, marginBottom: 12, alignItems: 'center' },
  scoutEyebrow: { color: '#7f8792', fontSize: 11, fontWeight: '700', letterSpacing: 1.5 },
  scoutLarge: { color: '#e8a33c', fontSize: 64, fontWeight: '900', marginTop: 6 },
  scoutRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#181b21', borderRadius: 13, borderWidth: 1, borderColor: '#262a33', padding: 12, marginBottom: 8 },
  scoutVal: { fontSize: 16, fontWeight: '800' },
  eventBanner: { borderRadius: 16, borderWidth: 1, padding: 14, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  eventEyebrow: { color: '#8890a0', fontSize: 11, fontWeight: '700', letterSpacing: 1, marginBottom: 5 },
  eventStatus: { fontSize: 26, fontWeight: '900', letterSpacing: -0.4 },
  scoreStack: { minWidth: 90, alignItems: 'center', marginHorizontal: 20 },
  matchCard: { backgroundColor: '#181b21', borderRadius: 18, padding: 16, marginTop: 16, borderWidth: 1, borderColor: '#262a33' },
  holeGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 8 },
  holeCell: { width: '11%', alignItems: 'center', marginBottom: 8, marginRight: 2 },
  holeCellNumber: { color: '#5f6672', fontSize: 9, fontWeight: '700' },
  holeCellValue: { width: 28, height: 28, borderRadius: 6, alignItems: 'center', justifyContent: 'center', marginTop: 4 },
  holeCellValueSmall: { width: 24, height: 20, borderRadius: 6, alignItems: 'center', justifyContent: 'center', marginTop: 3 },
  holeCellText: { fontSize: 13, fontWeight: '800' },
  holeCellTextSmall: { fontSize: 12, fontWeight: '700' },
  leaderRow: { flexDirection: 'row', alignItems: 'center', borderRadius: 11, borderWidth: 1, padding: 9, marginBottom: 6 },
  leaderPos: { width: 22, color: '#7f8792', fontSize: 15, fontWeight: '900', textAlign: 'center' },
  leaderName: { flex: 1, color: '#e5e8ed', fontSize: 14, fontWeight: '600' },
  leaderScore: { fontSize: 15, fontWeight: '800' },
  summaryCard: { borderRadius: 18, borderWidth: 1, padding: 18, marginBottom: 16 },
  summaryEyebrow: { color: '#8890a0', fontSize: 11, fontWeight: '700', letterSpacing: 1.5, textAlign: 'center' },
  summaryHeadline: { fontSize: 28, fontWeight: '900', marginTop: 6, textAlign: 'center' },
  summaryScores: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 12 },
  summarySide: { flex: 1, alignItems: 'center' },
  summarySchool: { color: '#e5e8ed', fontSize: 12.5, fontWeight: '600' },
  summaryScore: { color: '#9aa0ab', fontSize: 34, fontWeight: '900', lineHeight: 34 },
  summaryDash: { color: '#5f6672', fontSize: 13, fontWeight: '700', marginHorizontal: 12 },
  summaryHint: { color: '#828a96', fontSize: 11.5, textAlign: 'center', marginTop: 10, lineHeight: 16 },
  pairingRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#161920', borderRadius: 12, borderWidth: 1, borderColor: '#20232b', padding: 10, marginBottom: 8 },
});
